import { StyleSheet } from 'react-native';
import { SPACING, COLORS } from '@/constants';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: COLORS.BACKGROUND_SECONDARY,
    paddingBottom: SPACING.MD,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: SPACING.MD,
    paddingVertical: SPACING.SM,
    position: 'relative',
  },
  menuWithAvatarPill: {
    position: 'absolute',
    left: SPACING.MD,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.SECONDARY.PURE,
    borderRadius: 24,
    paddingLeft: 10,
    paddingRight: 6,
    paddingVertical: 6,
    zIndex: 1,
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 5,
  },
  menuIcon: {
    marginRight: 8,
  },
  menuIconImage: {
    width: 22,
    height: 22,
    marginRight: 8,
  },
  headerAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
  },
  headerAvatarPlaceholder: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.NEUTRAL.LOW.LIGHT,
    justifyContent: 'center',
    alignItems: 'center',
  },
  leftButton: {
    position: 'absolute',
    left: SPACING.MD,
    zIndex: 1,
  },
  rightButtons: {
    position: 'absolute',
    right: SPACING.MD,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.SM,
    zIndex: 1,
  },
  cartButtonWrapper: {
    position: 'relative',
  },
  cartBadge: {
    position: 'absolute',
    top: -2,
    right: -2,
    minWidth: 20,
    height: 18,
    paddingHorizontal: 5,
    borderRadius: 9,
    backgroundColor: COLORS.FEEDBACK.NOTIFICATION_PURE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cartBadgeText: {
    color: COLORS.WHITE,
    fontSize: 10,
    fontFamily: 'DM Sans',
    fontWeight: '700',
  },
  bellUnreadDot: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.FEEDBACK.WARNING,
  },
  rightLabelButton: {
    position: 'absolute',
    right: SPACING.MD,
    paddingVertical: SPACING.SM,
    paddingHorizontal: SPACING.XS,
    zIndex: 1,
  },
  rightLabelText: {
    color: COLORS.NEUTRAL.LOW.PURE,
    fontFamily: 'DM Sans',
    fontSize: 16,
    fontWeight: '600',
  },
});
