import { StyleSheet } from 'react-native';
import { COLORS, SPACING } from '@/constants';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: '#fbf7e5',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 28,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 32,
    paddingTop: SPACING.MD,
    paddingBottom: SPACING.LG,
    paddingHorizontal: SPACING.MD,
    shadowColor: COLORS.BLACK,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 4,
  },
  contentContainer: {
    gap: SPACING.LG,
    marginBottom: SPACING.SM,
  },
  badgeContainer: {
    alignSelf: 'flex-start',
  },
  authorSection: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.XS,
    marginBottom: SPACING.SM,
  },
  authorSectionPinned: {
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  authorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.XS,
    flex: 1,
  },
  pinIcon: {
    width: 24,
    height: 24,
  },
  pinnedContainer: {
    backgroundColor: COLORS.PRIMARY.LIGHT,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
  },
  avatar: {
    width: 24,
    height: 24,
    borderRadius: 12,
  },
  avatarPlaceholder: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: COLORS.BACKGROUND,
    justifyContent: 'center',
    alignItems: 'center',
  },
  authorName: {
    fontSize: 12,
    fontWeight: '500',
    color: '#6e6a6a',
    letterSpacing: 0.2,
    lineHeight: 22,
  },
  titleContainer: {
    marginBottom: SPACING.XS,
  },
  title: {
    fontSize: 20,
    fontWeight: '400',
    color: '#001137',
  },
  description: {
    fontSize: 14,
    fontWeight: '400',
    color: '#6e6a6a',
    letterSpacing: 0.2,
    lineHeight: 20,
  },
  mediaContainer: {
    marginTop: SPACING.SM,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#e8e4d4',
    maxHeight: 320,
  },
  mediaImage: {
    width: '100%',
    height: 200,
  },
  mediaImageExpanded: {
    width: '100%',
    height: 240,
  },
  videoPosterInner: {
    position: 'relative',
    width: '100%',
  },
  playOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
  },
  videoPlaceholder: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#2a2a2a',
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: SPACING.SM,
  },
  footerLeft: {
    flexShrink: 0,
    alignItems: 'flex-start',
  },
  footerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.SM,
  },
  likeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.XS,
    minHeight: 24,
  },
  likeButtonDisabled: {
    opacity: 0.6,
  },
  likeIcon: {
    width: 24,
    height: 24,
  },
  likeCount: {
    fontFamily: 'DM Sans',
    fontSize: 10,
    fontWeight: '400',
    color: '#0154f8',
    letterSpacing: 0.2,
    lineHeight: 20,
  },
  seeMoreButton: {
    backgroundColor: 'rgba(240, 238, 225, 0.16)',
    borderWidth: 1,
    borderColor: '#001137',
    borderRadius: 18,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    paddingHorizontal: SPACING.MD,
    paddingVertical: 9,
    minHeight: 36,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'flex-start',
  },
  seeMoreButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#001137',
    textAlign: 'center',
  },
  commentsInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.XS,
  },
  shareButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  commentsCount: {
    fontSize: 12,
    fontWeight: '500',
    color: '#0154f8',
    letterSpacing: 0.2,
    lineHeight: 22,
  },
});
