import { StyleSheet } from 'react-native';
import { BORDER_RADIUS, COLORS, FONT_SIZES, SPACING, TYPOGRAPHY } from '@/constants';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    position: 'relative',
  },
  scrollView: {
    flex: 1,
    zIndex: 1,
  },
  scrollContent: {
    paddingHorizontal: SPACING.MD,
    paddingBottom: SPACING.XL,
  },
  scrollContentOrderStep: {
    flexGrow: 1,
    paddingHorizontal: 0,
    paddingBottom: SPACING.XXL * 1.5,
  },
  contentFloatingMenuReserve: {
    paddingBottom: SPACING.XXL * 1.5,
  },
  backgroundLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 0,
  },
  orderStepStepperPadding: {
    paddingHorizontal: SPACING.MD,
  },
  protocolBlockedMessage: {
    color: '#b42318',
    fontSize: FONT_SIZES.SM,
    lineHeight: 20,
    marginBottom: SPACING.MD,
    paddingHorizontal: SPACING.XS,
  },
  addressCard: {
    backgroundColor: '#fbf7e5',
    borderRadius: 28,
    padding: SPACING.MD,
    paddingTop: SPACING.LG,
    marginBottom: SPACING.LG,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 16,
    elevation: 4,
  },
  addressCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: SPACING.LG,
  },
  addressCardTitle: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#001137',
    letterSpacing: 0.2,
  },
  addressCardContent: {
    marginBottom: SPACING.LG,
  },
  /** Container para mensagem de erro acima do formulário (ex.: falha ao carregar endereço) */
  addressErrorContainer: {
    paddingVertical: SPACING.MD,
  },
  checkboxPaddingTop: {
    paddingTop: SPACING.LG,
  },
  addressText: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#6e6a6a',
    letterSpacing: 0.2,
    lineHeight: 20,
  },
  deliveriesTitle: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#000000',
    marginBottom: SPACING.MD,
  },
  /** Lista de itens do carrinho no passo endereço (sem padding horizontal para alinhar ao conteúdo) */
  cartItemsList: {
    gap: SPACING.MD,
    paddingHorizontal: 0,
  },
  addressSection: {
    marginBottom: SPACING.LG,
  },
  addressRow: {
    flexDirection: 'row',
    gap: 21,
    marginTop: SPACING.SM,
  },
  addressFieldHalf: {
    flex: 1,
  },
  /** Campo número ao lado do endereço (menor largura) */
  addressFieldNumber: {
    flex: 0.28,
    minWidth: 72,
  },
  cepLoadingWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.SM,
    marginTop: SPACING.XS,
  },
  cepLoadingText: {
    fontSize: FONT_SIZES.XS,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#6e6a6a',
  },
  paymentMethodSection: {
    marginBottom: SPACING.LG,
  },
  sectionTitle: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#000000',
    marginBottom: SPACING.SM,
  },
  paymentMethodOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.XL,
    marginTop: SPACING.SM,
  },
  walletPayButtons: {
    gap: SPACING.SM,
  },
  walletPayButton: {
    overflow: 'visible',
    paddingVertical: 12,
  },
  walletPayLabel: {
    flexShrink: 0,
    lineHeight: 22,
  },
  walletPayMarkSlot: {
    alignItems: 'center',
    height: 24,
    justifyContent: 'center',
    overflow: 'visible',
    width: 24,
  },
  walletPayButtonSelected: {
    borderColor: COLORS.PRIMARY.PURE,
  },
  walletPayOrRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: SPACING.SM,
    marginVertical: SPACING.MD,
  },
  walletPayOrLine: {
    backgroundColor: COLORS.TEXT,
    flex: 1,
    height: 1,
  },
  walletPayOrLabel: {
    color: COLORS.TEXT,
    fontFamily: 'DM Sans',
    fontSize: FONT_SIZES.SM,
    fontWeight: '500',
  },
  paymentMethodOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.SM,
  },
  radioButton: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#001137',
    backgroundColor: '#fdfbee',
    justifyContent: 'center',
    alignItems: 'center',
  },
  radioButtonSelected: {
    borderColor: '#0154f8',
    backgroundColor: '#fdfbee',
  },
  radioButtonInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#0154f8',
  },
  paymentMethodLabel: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#000000',
  },
  cardForm: {
    marginBottom: SPACING.LG,
    rowGap: SPACING.MD,
  },
  cardRow: {
    flexDirection: 'row',
    gap: 21,
    marginTop: SPACING.SM,
  },
  cardFieldHalf: {
    flex: 1,
  },
  purchaseMethodField: {
    width: '100%',
    alignSelf: 'stretch',
  },
  purchaseMethodValue: {
    flex: 1,
    ...TYPOGRAPHY.bodyMd,
    color: COLORS.TEXT_LIGHT,
  },
  purchaseMethodModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 17, 55, 0.4)',
    justifyContent: 'flex-end',
  },
  purchaseMethodSheet: {
    backgroundColor: COLORS.SECONDARY.LIGHT,
    borderTopLeftRadius: BORDER_RADIUS.XL,
    borderTopRightRadius: BORDER_RADIUS.XL,
    padding: SPACING.MD,
    paddingBottom: SPACING.LG,
    gap: SPACING.SM,
  },
  purchaseMethodOption: {
    paddingVertical: SPACING.MD_PLUS,
    paddingHorizontal: SPACING.MD,
    borderRadius: BORDER_RADIUS.LG,
  },
  purchaseMethodOptionSelected: {
    backgroundColor: COLORS.SECONDARY.PURE,
  },
  purchaseMethodOptionLabel: {
    ...TYPOGRAPHY.bodyMd,
    color: COLORS.TEXT,
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.SM,
    marginTop: SPACING.MD,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 2,
    borderWidth: 1,
    borderColor: '#001137',
    backgroundColor: '#fdfbee',
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxChecked: {
    borderColor: '#0154f8',
    backgroundColor: '#fdfbee',
  },
  checkboxLabel: {
    fontSize: FONT_SIZES.XS,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#6e6a6a',
  },
  savedCard: {
    alignItems: 'center',
    backgroundColor: COLORS.SECONDARY.LIGHT,
    borderRadius: BORDER_RADIUS.XL,
    borderWidth: 1,
    flexDirection: 'row',
    gap: SPACING.LG,
    padding: SPACING.MD,
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 16,
    elevation: 2,
  },
  savedCardSelected: {
    borderColor: COLORS.PRIMARY.PURE,
  },
  savedCardIdle: {
    borderColor: COLORS.TEXT_LIGHT,
  },
  savedCardBrandRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: SPACING.SM,
  },
  savedCardBody: {
    flex: 1,
    gap: 2,
  },
  savedCardBrand: {
    height: 40,
    width: 40,
  },
  savedCardBrandAmex: {
    height: 40,
    width: 50,
  },
  savedCardBrandFallback: {
    alignItems: 'center',
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  savedCardBrandFallbackText: {
    color: COLORS.TEXT,
    fontFamily: 'DM Sans',
    fontSize: FONT_SIZES.XS,
    fontWeight: '700',
  },
  savedCardNumber: {
    color: COLORS.TEXT_LIGHT,
    flex: 1,
    fontFamily: 'DM Sans',
    fontSize: FONT_SIZES.SM,
    fontWeight: '400',
    letterSpacing: 0.2,
  },
  savedCardName: {
    color: COLORS.TEXT,
    fontFamily: 'DM Sans',
    fontSize: FONT_SIZES.XS,
    fontWeight: '500',
  },
  savedCardMeta: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  savedCardValidity: {
    color: COLORS.TEXT_LIGHT,
    fontFamily: 'DM Sans',
    fontSize: 8,
    lineHeight: 22,
  },
  savedCardBadge: {
    backgroundColor: COLORS.HIGHLIGHT.LIGHT,
    borderRadius: BORDER_RADIUS.ROUND,
    paddingHorizontal: SPACING.SM,
    paddingVertical: 2,
  },
  savedCardBadgeText: {
    color: COLORS.TEXT,
    fontFamily: 'DM Sans',
    fontSize: FONT_SIZES.XS,
    fontWeight: '500',
  },
  useAnotherCardButton: {
    alignSelf: 'stretch',
  },
  cardSheetBackdrop: {
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  cardSheetDismiss: {
    flex: 1,
  },
  cardSheet: {
    backgroundColor: COLORS.SECONDARY.LIGHT,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    gap: SPACING.LG,
    paddingHorizontal: SPACING.MD,
    paddingVertical: SPACING.LG,
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 4,
  },
  cardSheetHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  cardSheetTitle: {
    color: COLORS.TEXT,
    flex: 1,
    fontFamily: 'DM Sans',
    fontSize: FONT_SIZES.SM,
    fontWeight: '500',
  },
  cardSheetList: {
    gap: SPACING.MD,
  },
  cardSheetForm: {
    gap: SPACING.MD,
  },
  couponSection: {
    paddingVertical: SPACING.MD,
    marginBottom: SPACING.LG,
  },
  couponRow: {
    flexDirection: 'row',
    gap: SPACING.XS,
    marginTop: SPACING.SM,
    alignItems: 'flex-start',
  },
  applyButtonWrap: {
    alignSelf: 'flex-start',
  },
  couponInput: {
    flex: 1,
  },
  couponInputField: {
    height: 42,
  },
  couponAppliedBlock: {
    marginTop: SPACING.SM,
    gap: SPACING.SM,
  },
  couponAppliedText: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    color: '#0154f8',
    fontWeight: '500',
  },
  removeCouponButton: {
    alignSelf: 'flex-start',
  },
  applyButton: {
    backgroundColor: '#001137',
    paddingHorizontal: SPACING.MD,
    paddingVertical: 9,
    borderRadius: 18,
    minHeight: 36,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  applyButtonText: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#FFFFFF',
  },
  orderSummary: {
    marginTop: SPACING.LG,
  },
  separator: {
    height: 1,
    backgroundColor: '#e1dfcf',
    marginVertical: SPACING.SM,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: SPACING.XS,
  },
  summaryLabel: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#000000',
    letterSpacing: 0.2,
  },
  summaryValue: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#000000',
    letterSpacing: 0.2,
  },
  summaryTotalLabel: {
    fontWeight: '500',
  },
  summaryTotalValue: {
    fontWeight: '500',
  },
  buttonContainer: {
    paddingHorizontal: SPACING.MD,
    paddingBottom: SPACING.MD,
    paddingTop: SPACING.SM,
    zIndex: 1,
  },
  /** Texto de erro em vermelho abaixo de campos/seções */
  fieldError: {
    fontSize: FONT_SIZES.SM,
    color: '#b00',
    marginTop: SPACING.XS,
    marginBottom: SPACING.SM,
  },
  editAddressContainer: {
    marginBottom: SPACING.LG,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 16,
    elevation: 4,
    rowGap: SPACING.MD,
  },
  editAddressActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.SM,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: SPACING.MD,
    paddingTop: SPACING.MD,
  },
  cancelButton: {
    paddingHorizontal: SPACING.MD,
    paddingVertical: SPACING.SM,
    borderRadius: 18,
  },
  cancelButtonText: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#6e6a6a',
  },
  saveButton: {
    backgroundColor: '#001137',
    paddingHorizontal: SPACING.MD,
    paddingVertical: SPACING.SM,
    borderRadius: 18,
    minHeight: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  saveButtonText: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#FFFFFF',
  },
  // Order Screen Styles
  orderSummarySection: {
    marginBottom: SPACING.LG,
  },
  orderSummaryTitle: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#000000',
    marginBottom: SPACING.XS,
  },
  orderId: {
    fontSize: FONT_SIZES.MD,
    fontFamily: 'DM Sans',
    fontWeight: '700',
    color: '#001137',
    marginBottom: SPACING.MD,
  },
  orderSummaryDetails: {
    marginTop: SPACING.SM,
  },
  deliveryAddressCard: {
    backgroundColor: '#fbf7e5',
    borderRadius: 28,
    padding: SPACING.MD,
    paddingTop: SPACING.LG,
    marginBottom: SPACING.LG,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 16,
    elevation: 4,
  },
  deliveryAddressTitle: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#001137',
    letterSpacing: 0.2,
    marginBottom: SPACING.MD,
  },
  deliveryAddressContent: {
    marginBottom: SPACING.MD,
  },
  deliveryAddressText: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#6e6a6a',
    letterSpacing: 0.2,
    lineHeight: 20,
    marginBottom: SPACING.XS,
  },
  yourProductsTitle: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#000000',
    marginBottom: SPACING.MD,
  },
  orderItemsList: {
    marginBottom: SPACING.LG,
  },
  orderItemCard: {
    flexDirection: 'row',
    backgroundColor: '#fbf7e5',
    borderRadius: 28,
    padding: SPACING.MD,
    marginBottom: SPACING.MD,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 16,
    elevation: 4,
  },
  orderItemImage: {
    width: 100,
    height: 100,
    borderRadius: 16,
    marginRight: SPACING.MD,
  },
  orderItemContent: {
    flex: 1,
  },
  orderItemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: SPACING.XS,
  },
  orderItemTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.XS,
    flex: 1,
  },
  orderItemTag: {
    backgroundColor: '#001137',
    paddingHorizontal: SPACING.SM,
    paddingVertical: 4,
    borderRadius: 12,
  },
  orderItemTagText: {
    fontSize: FONT_SIZES.XS,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#FFFFFF',
  },
  orderItemTitle: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#001137',
    marginBottom: SPACING.XS,
  },
  orderItemDate: {
    fontSize: FONT_SIZES.XS,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#6e6a6a',
    marginBottom: SPACING.XS,
  },
  orderItemDeliveryForecast: {
    fontSize: FONT_SIZES.XS,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#6e6a6a',
    marginBottom: SPACING.XS,
    lineHeight: 16,
  },
  orderItemFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: SPACING.XS,
    marginBottom: SPACING.XS,
  },
  orderItemPrice: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#001137',
  },
  orderItemQuantity: {
    fontSize: FONT_SIZES.XS,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#6e6a6a',
  },
  orderItemActionButton: {
    borderWidth: 1,
    borderColor: '#001137',
    borderRadius: 18,
    paddingVertical: SPACING.XS,
    paddingHorizontal: SPACING.SM,
    alignSelf: 'flex-start',
    marginTop: SPACING.XS,
  },
  orderItemActionButtonText: {
    fontSize: FONT_SIZES.XS,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#001137',
  },
});
