import { StyleSheet } from 'react-native';
import { SPACING, FONT_SIZES } from '@/constants';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    position: 'relative',
  },
  scrollView: {
    flex: 1,
    zIndex: 1,
  },
  scrollContent: {
    paddingHorizontal: SPACING.MD,
    paddingBottom: SPACING.XL,
  },
  scrollContentOrderStep: {
    flexGrow: 1,
    paddingHorizontal: 0,
    paddingBottom: SPACING.XXL * 1.5,
  },
  contentFloatingMenuReserve: {
    paddingBottom: SPACING.XXL * 1.5,
  },
  backgroundLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 0,
  },
  orderStepStepperPadding: {
    paddingHorizontal: SPACING.MD,
  },
  protocolBlockedMessage: {
    color: '#b42318',
    fontSize: FONT_SIZES.SM,
    lineHeight: 20,
    marginBottom: SPACING.MD,
    paddingHorizontal: SPACING.XS,
  },
  addressCard: {
    backgroundColor: '#fbf7e5',
    borderRadius: 28,
    padding: SPACING.MD,
    paddingTop: SPACING.LG,
    marginBottom: SPACING.LG,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 16,
    elevation: 4,
  },
  addressCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: SPACING.LG,
  },
  addressCardTitle: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#001137',
    letterSpacing: 0.2,
  },
  addressCardContent: {
    marginBottom: SPACING.LG,
  },
  /** Container para mensagem de erro acima do formulário (ex.: falha ao carregar endereço) */
  addressErrorContainer: {
    paddingVertical: SPACING.MD,
  },
  checkboxPaddingTop: {
    paddingTop: SPACING.LG,
  },
  addressText: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#6e6a6a',
    letterSpacing: 0.2,
    lineHeight: 20,
  },
  deliveriesTitle: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#000000',
    marginBottom: SPACING.MD,
  },
  /** Lista de itens do carrinho no passo endereço (sem padding horizontal para alinhar ao conteúdo) */
  cartItemsList: {
    gap: SPACING.MD,
    paddingHorizontal: 0,
  },
  addressSection: {
    marginBottom: SPACING.LG,
  },
  addressRow: {
    flexDirection: 'row',
    gap: 21,
    marginTop: SPACING.SM,
  },
  addressFieldHalf: {
    flex: 1,
  },
  /** Campo número ao lado do endereço (menor largura) */
  addressFieldNumber: {
    flex: 0.28,
    minWidth: 72,
  },
  cepLoadingWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.SM,
    marginTop: SPACING.XS,
  },
  cepLoadingText: {
    fontSize: FONT_SIZES.XS,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#6e6a6a',
  },
  paymentMethodSection: {
    marginBottom: SPACING.LG,
  },
  sectionTitle: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#000000',
    marginBottom: SPACING.SM,
  },
  paymentMethodOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.XL,
    marginTop: SPACING.SM,
  },
  paymentMethodOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.SM,
  },
  radioButton: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#001137',
    backgroundColor: '#fdfbee',
    justifyContent: 'center',
    alignItems: 'center',
  },
  radioButtonSelected: {
    borderColor: '#0154f8',
    backgroundColor: '#fdfbee',
  },
  radioButtonInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#0154f8',
  },
  paymentMethodLabel: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#000000',
  },
  cardForm: {
    marginBottom: SPACING.LG,
    rowGap: SPACING.MD,
  },
  cardRow: {
    flexDirection: 'row',
    gap: 21,
    marginTop: SPACING.SM,
  },
  cardFieldHalf: {
    flex: 1,
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.SM,
    marginTop: SPACING.MD,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 2,
    borderWidth: 1,
    borderColor: '#001137',
    backgroundColor: '#fdfbee',
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxChecked: {
    borderColor: '#0154f8',
    backgroundColor: '#fdfbee',
  },
  checkboxLabel: {
    fontSize: FONT_SIZES.XS,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#6e6a6a',
  },
  couponSection: {
    paddingVertical: SPACING.MD,
    marginBottom: SPACING.LG,
  },
  couponRow: {
    flexDirection: 'row',
    gap: SPACING.XS,
    marginTop: SPACING.SM,
    alignItems: 'flex-start',
  },
  applyButtonWrap: {
    alignSelf: 'flex-start',
  },
  couponInput: {
    flex: 1,
  },
  couponInputField: {
    height: 42,
  },
  couponAppliedBlock: {
    marginTop: SPACING.SM,
    gap: SPACING.SM,
  },
  couponAppliedText: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    color: '#0154f8',
    fontWeight: '500',
  },
  removeCouponButton: {
    alignSelf: 'flex-start',
  },
  applyButton: {
    backgroundColor: '#001137',
    paddingHorizontal: SPACING.MD,
    paddingVertical: 9,
    borderRadius: 18,
    minHeight: 36,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  applyButtonText: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#FFFFFF',
  },
  orderSummary: {
    marginTop: SPACING.LG,
  },
  separator: {
    height: 1,
    backgroundColor: '#e1dfcf',
    marginVertical: SPACING.SM,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: SPACING.XS,
  },
  summaryLabel: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#000000',
    letterSpacing: 0.2,
  },
  summaryValue: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#000000',
    letterSpacing: 0.2,
  },
  summaryTotalLabel: {
    fontWeight: '500',
  },
  summaryTotalValue: {
    fontWeight: '500',
  },
  buttonContainer: {
    paddingHorizontal: SPACING.MD,
    paddingBottom: SPACING.MD,
    paddingTop: SPACING.SM,
    zIndex: 1,
  },
  /** Texto de erro em vermelho abaixo de campos/seções */
  fieldError: {
    fontSize: FONT_SIZES.SM,
    color: '#b00',
    marginTop: SPACING.XS,
    marginBottom: SPACING.SM,
  },
  editAddressContainer: {
    marginBottom: SPACING.LG,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 16,
    elevation: 4,
    rowGap: SPACING.MD,
  },
  editAddressActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.SM,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: SPACING.MD,
    paddingTop: SPACING.MD,
  },
  cancelButton: {
    paddingHorizontal: SPACING.MD,
    paddingVertical: SPACING.SM,
    borderRadius: 18,
  },
  cancelButtonText: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#6e6a6a',
  },
  saveButton: {
    backgroundColor: '#001137',
    paddingHorizontal: SPACING.MD,
    paddingVertical: SPACING.SM,
    borderRadius: 18,
    minHeight: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  saveButtonText: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#FFFFFF',
  },
  // Order Screen Styles
  orderSummarySection: {
    marginBottom: SPACING.LG,
  },
  orderSummaryTitle: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#000000',
    marginBottom: SPACING.XS,
  },
  orderId: {
    fontSize: FONT_SIZES.MD,
    fontFamily: 'DM Sans',
    fontWeight: '700',
    color: '#001137',
    marginBottom: SPACING.MD,
  },
  orderSummaryDetails: {
    marginTop: SPACING.SM,
  },
  deliveryAddressCard: {
    backgroundColor: '#fbf7e5',
    borderRadius: 28,
    padding: SPACING.MD,
    paddingTop: SPACING.LG,
    marginBottom: SPACING.LG,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 16,
    elevation: 4,
  },
  deliveryAddressTitle: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#001137',
    letterSpacing: 0.2,
    marginBottom: SPACING.MD,
  },
  deliveryAddressContent: {
    marginBottom: SPACING.MD,
  },
  deliveryAddressText: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#6e6a6a',
    letterSpacing: 0.2,
    lineHeight: 20,
    marginBottom: SPACING.XS,
  },
  yourProductsTitle: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#000000',
    marginBottom: SPACING.MD,
  },
  orderItemsList: {
    marginBottom: SPACING.LG,
  },
  orderItemCard: {
    flexDirection: 'row',
    backgroundColor: '#fbf7e5',
    borderRadius: 28,
    padding: SPACING.MD,
    marginBottom: SPACING.MD,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 16,
    elevation: 4,
  },
  orderItemImage: {
    width: 100,
    height: 100,
    borderRadius: 16,
    marginRight: SPACING.MD,
  },
  orderItemContent: {
    flex: 1,
  },
  orderItemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: SPACING.XS,
  },
  orderItemTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.XS,
    flex: 1,
  },
  orderItemTag: {
    backgroundColor: '#001137',
    paddingHorizontal: SPACING.SM,
    paddingVertical: 4,
    borderRadius: 12,
  },
  orderItemTagText: {
    fontSize: FONT_SIZES.XS,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#FFFFFF',
  },
  orderItemTitle: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#001137',
    marginBottom: SPACING.XS,
  },
  orderItemDate: {
    fontSize: FONT_SIZES.XS,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#6e6a6a',
    marginBottom: SPACING.XS,
  },
  orderItemDeliveryForecast: {
    fontSize: FONT_SIZES.XS,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#6e6a6a',
    marginBottom: SPACING.XS,
    lineHeight: 16,
  },
  orderItemFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: SPACING.XS,
    marginBottom: SPACING.XS,
  },
  orderItemPrice: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#001137',
  },
  orderItemQuantity: {
    fontSize: FONT_SIZES.XS,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#6e6a6a',
  },
  orderItemActionButton: {
    borderWidth: 1,
    borderColor: '#001137',
    borderRadius: 18,
    paddingVertical: SPACING.XS,
    paddingHorizontal: SPACING.SM,
    alignSelf: 'flex-start',
    marginTop: SPACING.XS,
  },
  orderItemActionButtonText: {
    fontSize: FONT_SIZES.XS,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#001137',
  },
});
