import { StyleSheet } from 'react-native';
import { COLORS, FONT_FAMILY, SPACING, TYPOGRAPHY } from '@/constants';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingBottom: 0,
  },
  scrollContent: {
    flexGrow: 1,
    paddingTop: SPACING.LG,
    paddingHorizontal: SPACING.GAP_20,
    paddingBottom: SPACING.GAP_20,
    gap: SPACING.MD,
  },
  scrollContentReason: {
    gap: SPACING.XL,
  },
  title: {
    ...TYPOGRAPHY.title3,
    color: COLORS.TEXT,
  },
  overviewBody: {
    flexGrow: 1,
    gap: SPACING.XL,
    width: '100%',
  },
  description: {
    ...TYPOGRAPHY.bodyMd,
    color: COLORS.TEXT,
  },
  removedList: {
    flexGrow: 1,
    width: '100%',
  },
  removedItemBlock: {
    gap: SPACING.MD_PLUS,
    width: '100%',
  },
  removedItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: SPACING.MD_PLUS,
    width: '100%',
  },
  removedItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.MD_PLUS,
    flexShrink: 1,
  },
  removedItemLabel: {
    ...TYPOGRAPHY.bodyMd,
    color: COLORS.TEXT,
    flexShrink: 1,
  },
  removedItemStatus: {
    ...TYPOGRAPHY.bodySm,
    lineHeight: 16,
    color: COLORS.TEXT_LIGHT,
  },
  separator: {
    height: 1,
    width: '100%',
    backgroundColor: COLORS.SECONDARY.MEDIUM,
  },
  attentionCard: {
    width: '100%',
    backgroundColor: COLORS.HIGHLIGHT.LIGHT,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 32,
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 24,
    padding: SPACING.LG,
    gap: SPACING.MD,
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  attentionTitle: {
    fontFamily: FONT_FAMILY.DM_SANS_BOLD,
    fontSize: 16,
    lineHeight: 22,
    color: COLORS.TEXT,
  },
  attentionBody: {
    ...TYPOGRAPHY.bodyMd,
    color: COLORS.TEXT,
  },
  reasonSection: {
    width: '100%',
    gap: SPACING.MD_PLUS,
  },
  reasonTitleRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'baseline',
    gap: SPACING.XS,
  },
  reasonTitle: {
    fontFamily: FONT_FAMILY.DM_SANS_BOLD,
    fontSize: 16,
    lineHeight: 22,
    color: COLORS.TEXT,
  },
  reasonOptional: {
    ...TYPOGRAPHY.bodyMd,
    color: COLORS.TEXT_LIGHT,
  },
  reasonList: {
    width: '100%',
    gap: SPACING.SM,
  },
  reasonOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.MD_PLUS,
    padding: SPACING.MD,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.SECONDARY.MEDIUM,
    backgroundColor: COLORS.WHITE,
  },
  reasonOptionSelected: {
    borderColor: COLORS.PRIMARY.PURE,
    backgroundColor: COLORS.SECONDARY.LIGHT,
  },
  reasonRadio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.TEXT,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.WHITE,
  },
  reasonRadioSelected: {
    borderColor: COLORS.PRIMARY.PURE,
    padding: 4,
  },
  reasonRadioInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: COLORS.PRIMARY.PURE,
  },
  reasonLabel: {
    flex: 1,
    ...TYPOGRAPHY.bodyMd,
    color: COLORS.TEXT,
  },
  actions: {
    gap: SPACING.MD_PLUS,
    marginTop: 'auto',
    width: '100%',
  },
  modalFooter: {
    gap: SPACING.MD_PLUS,
    width: '100%',
    marginTop: SPACING.LG,
  },
  modalTitle: {
    ...TYPOGRAPHY.title3,
    color: COLORS.TEXT,
    marginBottom: SPACING.MD,
  },
  modalInstruction: {
    ...TYPOGRAPHY.bodyMd,
    color: COLORS.TEXT,
    marginBottom: SPACING.LG,
  },
  modalInstructionHighlight: {
    fontFamily: FONT_FAMILY.DM_SANS_BOLD,
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.2,
    color: COLORS.ERROR,
  },
  confirmInput: {
    width: '100%',
    borderRadius: 18,
    paddingHorizontal: SPACING.MD,
    paddingVertical: SPACING.MD_PLUS,
    fontFamily: FONT_FAMILY.DM_SANS_REGULAR,
    fontSize: 14,
    letterSpacing: 0.2,
    color: COLORS.TEXT,
    backgroundColor: COLORS.SECONDARY.LIGHT,
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
});
