import { StyleSheet } from 'react-native';
import { COLORS, SPACING } from '@/constants';

export const styles = StyleSheet.create({
  modalRoot: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.36)',
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  panel: {
    flex: 1,
    maxWidth: 341,
    width: '87%',
    backgroundColor: COLORS.SECONDARY.PURE,
    borderTopRightRadius: 32,
    borderBottomRightRadius: 32,
    paddingHorizontal: SPACING.GAP_20,
    paddingTop: 52,
    paddingBottom: SPACING.MD_PLUS,
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 6,
  },
  profileMenu: {
    flex: 1,
    paddingVertical: SPACING.SM,
    gap: SPACING.GAP_20,
  },
  closeButton: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  avatarWithText: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingRight: 28,
    maxWidth: 249,
  },
  avatar: {
    width: 39,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.NEUTRAL.LOW.LIGHT,
  },
  avatarPlaceholder: {
    width: 39,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.NEUTRAL.LOW.LIGHT,
  },
  userDetails: {
    flexShrink: 1,
    justifyContent: 'center',
  },
  userName: {
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.2,
    color: COLORS.TEXT,
    fontWeight: '400',
    fontFamily: 'DM Sans',
  },
  userEmail: {
    fontSize: 12,
    lineHeight: 22,
    letterSpacing: 0.2,
    color: COLORS.TEXT_LIGHT,
    fontWeight: '500',
    fontFamily: 'DM Sans',
  },
  itemsContainer: {
    flex: 1,
    width: '100%',
  },
  menuItemBlock: {
    paddingTop: SPACING.LG,
    gap: SPACING.MD,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  menuItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.SM,
    flex: 1,
  },
  menuItemLabel: {
    fontSize: 16,
    lineHeight: 24,
    color: COLORS.TEXT,
    fontWeight: '700',
    fontFamily: 'DM Sans',
    flexShrink: 1,
  },
  separator: {
    height: 1,
    backgroundColor: COLORS.SECONDARY.MEDIUM,
    width: '100%',
  },
  bottomButtons: {
    gap: SPACING.SM,
    width: '100%',
  },
});
