import { StyleSheet } from 'react-native';
import { BORDER_RADIUS, COLORS, FONT_FAMILY, FONT_SIZES, SPACING, TYPOGRAPHY } from '@/constants';

const cardRadius = {
  borderTopLeftRadius: BORDER_RADIUS.XL,
  borderTopRightRadius: 28,
  borderBottomRightRadius: SPACING.XL,
  borderBottomLeftRadius: BORDER_RADIUS.MD,
};

export const styles = StyleSheet.create({
  listRoot: {
    paddingHorizontal: SPACING.MD,
    paddingTop: SPACING.LG,
    gap: SPACING.LG,
  },
  listIntro: {
    paddingHorizontal: SPACING.MD,
    gap: SPACING.SM,
  },
  listTitle: {
    ...TYPOGRAPHY.displaySm,
    color: COLORS.NEUTRAL.LOW.PURE,
    textTransform: 'uppercase',
  },
  listSubtitle: {
    fontFamily: FONT_FAMILY.DM_SANS_MEDIUM,
    fontSize: FONT_SIZES.XS,
    lineHeight: 16,
    color: COLORS.NEUTRAL.LOW.PURE,
  },
  typeList: {
    gap: SPACING.MD,
  },
  typeCard: {
    height: 164,
    backgroundColor: COLORS.NEUTRAL.LOW.PURE,
    ...cardRadius,
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 16,
    elevation: 2,
  },
  typeMedia: {
    ...StyleSheet.absoluteFillObject,
    overflow: 'hidden',
    ...cardRadius,
  },
  typePhoto: {
    ...StyleSheet.absoluteFillObject,
  },
  typeShade: {
    ...StyleSheet.absoluteFillObject,
  },
  typeRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    padding: SPACING.MD,
    gap: SPACING.SM,
  },
  typeTitle: {
    ...TYPOGRAPHY.labelLg,
    color: COLORS.WHITE,
    flex: 1,
  },
  typeChevron: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.SECONDARY.LIGHT,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  filterRow: {
    gap: SPACING.MD,
    paddingHorizontal: SPACING.MD,
    alignItems: 'center',
  },
  moduleChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    minHeight: 36,
    paddingHorizontal: SPACING.MD,
    paddingVertical: SPACING.SM,
    borderWidth: 1,
    borderColor: COLORS.PRIMARY.PURE,
    backgroundColor: 'rgba(240,238,225,0.16)',
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderBottomRightRadius: BORDER_RADIUS.LG,
    borderBottomLeftRadius: BORDER_RADIUS.LG,
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  moduleChipLabel: {
    fontFamily: FONT_FAMILY.DM_SANS_MEDIUM,
    fontSize: FONT_SIZES.SM,
    color: COLORS.PRIMARY.PURE,
  },
  sortChip: {
    minHeight: 36,
    justifyContent: 'center',
    paddingHorizontal: SPACING.MD,
    paddingVertical: SPACING.SM,
    backgroundColor: COLORS.SECONDARY.LIGHT,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderBottomRightRadius: BORDER_RADIUS.LG,
    borderBottomLeftRadius: BORDER_RADIUS.LG,
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  sortChipSelected: {
    minHeight: 36,
    justifyContent: 'center',
    paddingHorizontal: SPACING.MD,
    paddingVertical: SPACING.SM,
    backgroundColor: COLORS.PRIMARY.PURE,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderBottomRightRadius: BORDER_RADIUS.LG,
    borderBottomLeftRadius: BORDER_RADIUS.LG,
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  sortChipLabel: {
    fontFamily: FONT_FAMILY.DM_SANS_MEDIUM,
    fontSize: FONT_SIZES.SM,
    color: COLORS.NEUTRAL.LOW.PURE,
  },
  sortChipLabelSelected: {
    fontFamily: FONT_FAMILY.DM_SANS_MEDIUM,
    fontSize: FONT_SIZES.SM,
    color: COLORS.SECONDARY.PURE,
  },
  moduleMenu: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.SM,
    paddingHorizontal: SPACING.MD,
  },
  moduleMenuItem: {
    paddingHorizontal: SPACING.MD,
    paddingVertical: SPACING.SM,
    borderRadius: BORDER_RADIUS.LG,
    backgroundColor: COLORS.SECONDARY.LIGHT,
  },
  moduleMenuItemSelected: {
    paddingHorizontal: SPACING.MD,
    paddingVertical: SPACING.SM,
    borderRadius: BORDER_RADIUS.LG,
    backgroundColor: COLORS.PRIMARY.PURE,
  },
  moduleMenuLabel: {
    fontFamily: FONT_FAMILY.DM_SANS_MEDIUM,
    fontSize: FONT_SIZES.SM,
    color: COLORS.NEUTRAL.LOW.PURE,
  },
  moduleMenuLabelSelected: {
    fontFamily: FONT_FAMILY.DM_SANS_MEDIUM,
    fontSize: FONT_SIZES.SM,
    color: COLORS.SECONDARY.PURE,
  },
  contentCard: {
    height: 471,
    justifyContent: 'space-between',
    paddingHorizontal: SPACING.LG,
    paddingVertical: SPACING.XL,
    backgroundColor: COLORS.NEUTRAL.LOW.PURE,
    borderTopLeftRadius: 64,
    borderTopRightRadius: 64,
    borderBottomRightRadius: SPACING.XL,
    borderBottomLeftRadius: SPACING.XL,
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 16,
    elevation: 2,
  },
  contentMedia: {
    ...StyleSheet.absoluteFillObject,
    overflow: 'hidden',
    borderTopLeftRadius: 64,
    borderTopRightRadius: 64,
    borderBottomRightRadius: SPACING.XL,
    borderBottomLeftRadius: SPACING.XL,
  },
  contentTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.MD_PLUS,
  },
  contentPlay: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    width: 64,
    height: 64,
    marginTop: -32,
    marginLeft: -32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  contentPlayIcon: {
    transform: [{ scale: 2.4 }],
  },
  contentFooter: {
    gap: SPACING.SM,
  },
  contentMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: SPACING.SM,
  },
  contentDate: {
    fontFamily: FONT_FAMILY.DM_SANS_BOLD,
    fontSize: 10,
    lineHeight: 22,
    letterSpacing: 0.2,
    color: COLORS.WHITE,
    textTransform: 'uppercase',
  },
  contentBadge: {
    minHeight: 24,
    justifyContent: 'center',
    paddingHorizontal: 14,
    backgroundColor: 'rgba(0,17,55,0.64)',
    borderTopLeftRadius: BORDER_RADIUS.MD,
    borderTopRightRadius: BORDER_RADIUS.MD,
    borderBottomRightRadius: 11,
    borderBottomLeftRadius: 11,
  },
  contentBadgeText: {
    fontFamily: FONT_FAMILY.DM_SANS_REGULAR,
    fontSize: 8,
    lineHeight: 22,
    letterSpacing: 0.2,
    color: COLORS.PRIMARY.LIGHT,
  },
  contentTitle: {
    fontFamily: FONT_FAMILY.BRICOLAGE_BOLD,
    fontSize: 20,
    lineHeight: 24,
    color: COLORS.WHITE,
    textTransform: 'uppercase',
  },
  contentSummary: {
    fontFamily: FONT_FAMILY.DM_SANS_MEDIUM,
    fontSize: FONT_SIZES.XS,
    lineHeight: 16,
    color: COLORS.WHITE,
  },
  empty: {
    ...TYPOGRAPHY.bodyMd,
    color: COLORS.NEUTRAL.LOW.PURE,
  },
});
