import { StyleSheet } from 'react-native';
import { BORDER_RADIUS, COLORS, FONT_FAMILY, FONT_SIZES, SPACING, TYPOGRAPHY } from '@/constants';

export const styles = StyleSheet.create({
  tabs: {
    marginHorizontal: SPACING.MD,
    zIndex: 1,
  },
  filters: {
    paddingVertical: SPACING.MD,
    zIndex: 1,
  },
  filtersContent: {
    paddingHorizontal: SPACING.MD,
    alignItems: 'center',
    gap: SPACING.MD,
  },
  sortButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    minHeight: 36,
    paddingHorizontal: SPACING.MD,
    paddingVertical: SPACING.SM,
    borderWidth: 1,
    borderColor: COLORS.PRIMARY.PURE,
    backgroundColor: COLORS.SECONDARY.PURE,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderBottomLeftRadius: BORDER_RADIUS.LG,
    borderBottomRightRadius: BORDER_RADIUS.LG,
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  sortLabel: {
    ...TYPOGRAPHY.labelMd,
    color: COLORS.PRIMARY.PURE,
  },
  sortIconOldest: {
    transform: [{ rotate: '180deg' }],
  },
  filterChip: {
    minHeight: 36,
    paddingHorizontal: SPACING.MD,
    paddingVertical: SPACING.SM,
    borderWidth: 0,
    backgroundColor: COLORS.SECONDARY.LIGHT,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderBottomLeftRadius: BORDER_RADIUS.LG,
    borderBottomRightRadius: BORDER_RADIUS.LG,
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  filterChipSelected: {
    minHeight: 36,
    paddingHorizontal: SPACING.MD,
    paddingVertical: SPACING.SM,
    borderWidth: 0,
    backgroundColor: COLORS.PRIMARY.PURE,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderBottomLeftRadius: BORDER_RADIUS.LG,
    borderBottomRightRadius: BORDER_RADIUS.LG,
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  emptyWrap: {
    paddingTop: SPACING.XL,
  },
  emptyMessage: {
    ...TYPOGRAPHY.bodyMd,
    color: COLORS.NEUTRAL.LOW.PURE,
    textAlign: 'center',
    paddingHorizontal: SPACING.LG,
    paddingVertical: SPACING.XL,
  },
  cards: {
    paddingHorizontal: SPACING.MD,
    gap: SPACING.MD,
    zIndex: 1,
  },
  section: {
    gap: SPACING.SM,
    zIndex: 1,
  },
  sectionTitle: {
    fontFamily: FONT_FAMILY.DM_SANS_SEMIBOLD,
    fontSize: FONT_SIZES.SM,
    letterSpacing: 0.2,
    color: COLORS.NEUTRAL.LOW.PURE,
    paddingHorizontal: SPACING.MD,
  },
  liveRow: {
    paddingHorizontal: SPACING.MD,
    gap: SPACING.SM,
  },
  eventsStack: {
    gap: SPACING.LG,
  },
});
