import { StyleSheet, Dimensions, type TextStyle } from 'react-native';
import { BORDER_RADIUS, COLORS, FLOATING_NAV_MENU_BAR_OFFSET, SPACING } from '@/constants';

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');

const textPreserveWhitespace: TextStyle = { whiteSpace: 'pre-wrap' } as TextStyle;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    position: 'relative',
  },
  backgroundImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
    zIndex: 0,
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    flex: 1,
  },
  backgroundImageStyle: {
    resizeMode: 'cover',
    opacity: 0.1,
  },
  heroSection: {
    width: SCREEN_WIDTH,
    height: SCREEN_HEIGHT * 0.6,
    position: 'relative',
    marginTop: -50,
  },
  heroOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    paddingHorizontal: 32,
    paddingBottom: 30,
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
  },
  heroGradient: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 327,
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
  },
  heroContent: {
    zIndex: 1,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
  },
  heroContentLeft: {
    flex: 1,
  },
  heroCartButton: {
    width: 53,
    height: 48,
    borderRadius: 24,
    backgroundColor: COLORS.NEUTRAL.HIGH.LIGHT,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  badgesContainer: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 10,
  },
  badge: {
    backgroundColor: 'rgba(0, 17, 55, 0.64)',
    paddingHorizontal: 14,
    paddingVertical: 0,
    borderRadius: 16,
    minHeight: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  badgeText: {
    fontSize: 12,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#f6dea9',
    letterSpacing: 0.2,
  },
  heroTitle: {
    fontSize: 20,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#FFFFFF',
    marginTop: 10,
  },
  heroPrice: {
    fontSize: 24,
    fontFamily: 'DM Sans',
    fontStyle: 'normal',
    fontWeight: '400',
    color: '#FFFFFF',
    lineHeight: 24,
    marginTop: 0,
  },
  heroFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: SPACING.MD,
  },
  paginationContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 5,
    marginTop: SPACING.MD,
    marginBottom: SPACING.LG,
  },
  paginationDot: {
    width: 10,
    height: 9,
    borderRadius: 4.5,
    backgroundColor: '#b2b2b2',
  },
  paginationDotActive: {
    backgroundColor: '#0154f8',
  },
  customHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: SPACING.MD,
    paddingTop: 50,
    paddingBottom: SPACING.SM,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 10,
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
  },
  logoContainer: {
    flex: 1,
    alignItems: 'center',
  },
  favoriteButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
  },
  scrollContent: {
    paddingBottom: SPACING.XL + FLOATING_NAV_MENU_BAR_OFFSET,
  },
  heroCardTags: {
    flexDirection: 'row',
    gap: SPACING.SM,
    flexWrap: 'wrap',
    marginBottom: SPACING.SM,
  },
  heroCardTag: {
    backgroundColor: '#2E7D32',
    borderRadius: 999,
    paddingHorizontal: SPACING.SM,
    paddingVertical: 4,
  },
  heroCardTagText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  heroCardTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#001137',
    marginBottom: SPACING.SM,
  },
  heroCardPriceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  heroCardPrice: {
    fontSize: 18,
    fontWeight: '700',
    color: '#001137',
  },
  heroCardCartButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F5F5F5',
    justifyContent: 'center',
    alignItems: 'center',
  },
  content: {
    backgroundColor: COLORS.BACKGROUND,
    paddingTop: SPACING.LG,
  },
  contactButtonsRow: {
    paddingHorizontal: SPACING.LG,
    marginBottom: 0,
  },
  swapperSection: {
    paddingHorizontal: SPACING.LG,
  },
  contentCard: {
    paddingHorizontal: SPACING.LG,
    paddingVertical: SPACING.LG,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: SPACING.LG,
  },
  contentBadge: {
    backgroundColor: 'rgba(0, 17, 55, 0.64)',
    paddingHorizontal: 14,
    paddingVertical: 0,
    borderRadius: 12,
    minHeight: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  contentBadgeText: {
    fontSize: 12,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: COLORS.PRIMARY.LIGHT,
    letterSpacing: 0.2,
    lineHeight: 22,
  },
  ratingBlock: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  ratingCount: {
    fontSize: 14,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: COLORS.NEUTRAL.LOW.PURE,
    letterSpacing: 0.2,
  },
  tabsContainerInCard: {
    paddingBottom: SPACING.LG,
  },
  tabsContainer: {
    marginBottom: SPACING.LG,
    paddingHorizontal: SPACING.MD,
  },
  productTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#000000',
    marginBottom: SPACING.MD,
  },
  sectionTitle: {
    fontSize: 14,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#001137',
    marginBottom: SPACING.MD,
  },
  productDescription: {
    fontSize: 15,
    lineHeight: 22,
    color: '#666666',
    marginBottom: SPACING.LG,
    paddingHorizontal: SPACING.LG,
    ...textPreserveWhitespace,
  },
  tabContent: {
    paddingHorizontal: SPACING.SM,
  },
  descriptionContainer: {
    gap: 8,
  },
  descriptionItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  bulletPoint: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: '#6e6a6a',
    marginTop: 8.5,
    flexShrink: 0,
  },
  descriptionText: {
    flex: 1,
    fontSize: 14,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#6e6a6a',
    letterSpacing: 0.2,
    lineHeight: 22,
    ...textPreserveWhitespace,
  },
  programAgreementsCheckboxRow: {
    marginTop: SPACING.LG,
    paddingHorizontal: SPACING.SM,
  },
  partnerSectionAbovePrice: {
    marginTop: SPACING.LG,
    gap: SPACING.MD,
  },
  partnerSectionAtScreenEnd: {
    paddingHorizontal: SPACING.LG,
    paddingBottom: SPACING.XL,
  },
  addToCartSecondary: {
    width: '100%',
    marginTop: SPACING.LG,
  },
  addToCartSecondaryBelowPrice: {
    width: '100%',
    marginTop: SPACING.MD,
  },
  addToCartSecondaryWrapper: {
    paddingHorizontal: SPACING.LG,
  },
  providerAvatarOutside: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  providerAvatarInButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  providerButtonContainer: {
    marginTop: SPACING.MD,
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
  },
  providerProfileButton: {
    width: '100%',
  },
  providerAvatarSmall: {
    width: 32,
    height: 32,
    borderRadius: 16,
  },
  providerButton: {
    backgroundColor: '#001137',
    borderRadius: BORDER_RADIUS.LG,
    padding: SPACING.MD,
    marginBottom: SPACING.LG,
    alignItems: 'center',
  },
  providerButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#000000',
  },
  videoSection: {
    marginBottom: SPACING.XL,
  },
  videoContainer: {
    width: '100%',
    height: 200,
    borderRadius: BORDER_RADIUS.LG,
    overflow: 'hidden',
    position: 'relative',
    marginBottom: SPACING.SM,
  },
  videoThumbnail: {
    width: '100%',
    height: '100%',
  },
  playButton: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: [{ translateX: -30 }, { translateY: -30 }],
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  downloadButton: {
    position: 'absolute',
    top: SPACING.MD,
    right: SPACING.MD,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    paddingHorizontal: SPACING.SM,
    paddingVertical: 6,
  },
  downloadButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#000000',
  },
  videoOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: SPACING.MD,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
  videoTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  videoDuration: {
    fontSize: 14,
    color: '#FFFFFF',
  },
  videoPagination: {
    flexDirection: 'row',
    gap: SPACING.XS,
    justifyContent: 'center',
    marginTop: SPACING.SM,
  },
  videoDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#CCCCCC',
  },
  videoDotActive: {
    backgroundColor: '#2196F3',
  },
  infoTabsContainer: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
    marginBottom: SPACING.LG,
  },
  infoTab: {
    paddingVertical: SPACING.MD,
    paddingHorizontal: SPACING.LG,
    marginRight: SPACING.LG,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  infoTabActive: {
    borderBottomColor: '#2196F3',
  },
  infoTabText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#666666',
  },
  infoTabTextActive: {
    color: '#2196F3',
    fontWeight: '600',
  },
  aboutContent: {
    paddingHorizontal: SPACING.MD,
    paddingVertical: SPACING.MD,
  },
  aboutItem: {
    fontSize: 15,
    lineHeight: 24,
    color: '#000000',
    marginBottom: SPACING.SM,
  },
  feedbackSection: {
    backgroundColor: '#DBE7DB',
    borderRadius: 20,
    padding: SPACING.LG,
  },
  feedbackHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: SPACING.MD,
  },
  feedbackTitle: {
    fontSize: 18,
    fontFamily: 'DM Sans',
    fontWeight: '700',
    color: '#001137',
  },
  feedbackRating: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  feedbackRatingText: {
    fontSize: 16,
    fontFamily: 'DM Sans',
    fontWeight: '600',
    color: '#001137',
  },
  reviewsList: {
    gap: SPACING.MD,
    marginBottom: SPACING.MD,
  },
  reviewCard: {
    backgroundColor: '#F9F7F4',
    borderRadius: 12,
    padding: SPACING.MD,
  },
  reviewUserName: {
    fontSize: 14,
    fontFamily: 'DM Sans',
    fontWeight: '700',
    color: '#001137',
    marginBottom: 4,
  },
  reviewComment: {
    fontSize: 14,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#001137',
    marginBottom: 8,
  },
  reviewFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  reviewDate: {
    fontSize: 12,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#666666',
  },
  reviewRating: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  reviewRatingText: {
    fontSize: 12,
    fontFamily: 'DM Sans',
    fontWeight: '600',
    color: '#001137',
  },
  seeAllButton: {
    alignItems: 'center',
    paddingVertical: SPACING.MD,
  },
  seeAllText: {
    fontSize: 14,
    fontFamily: 'DM Sans',
    fontWeight: '600',
    color: '#001137',
  },
  plansSection: {},
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: SPACING.XL,
  },
  loadingText: {
    marginTop: SPACING.MD,
    fontSize: 16,
    color: '#666666',
  },
  outOfStockBadge: {
    marginTop: SPACING.SM,
    backgroundColor: '#FFEBEE',
    borderRadius: BORDER_RADIUS.SM,
    padding: SPACING.SM,
    alignItems: 'center',
  },
  outOfStockText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#F44336',
  },
  productSku: {
    fontSize: 14,
    color: '#666666',
    marginTop: SPACING.SM,
  },
  productBrand: {
    fontSize: 14,
    color: '#666666',
    marginTop: SPACING.XS,
  },
  productWeight: {
    fontSize: 14,
    color: '#666666',
    marginTop: SPACING.XS,
  },
  communityPreviewContainer: {
    marginTop: SPACING.MD,
  },
  emptyContainer: {
    padding: SPACING.XL,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyText: {
    fontSize: 16,
    color: '#666666',
    textAlign: 'center',
  },
});
