import { StyleSheet } from 'react-native';
import { COLORS, FONT_SIZES, SPACING } from '@/constants';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: SPACING.MD,
    paddingBottom: SPACING.XXL,
  },
  titleSection: {
    alignItems: 'center',
    marginBottom: SPACING.LG,
    marginTop: SPACING.SM,
  },
  screenTitle: {
    fontSize: FONT_SIZES.XL,
    fontFamily: 'DM Sans',
    fontWeight: '700',
    color: COLORS.TEXT,
    marginBottom: SPACING.XS,
  },
  titleUnderline: {
    width: 85,
    height: 2,
    backgroundColor: COLORS.PRIMARY.PURE,
    borderRadius: 1,
  },
  orderNumberLabel: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: COLORS.BLACK,
    marginBottom: SPACING.XS,
  },
  orderNumber: {
    fontSize: FONT_SIZES.MD,
    fontFamily: 'DM Sans',
    fontWeight: '700',
    color: COLORS.TEXT,
    marginBottom: SPACING.LG,
  },
  summarySection: {
    marginBottom: SPACING.MD,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: SPACING.SM,
  },
  summaryLabel: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: COLORS.BLACK,
  },
  summaryValue: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: COLORS.BLACK,
  },
  summaryTotalLabel: {
    fontWeight: '700',
    color: COLORS.TEXT,
  },
  summaryTotalValue: {
    fontWeight: '700',
    color: COLORS.TEXT,
  },
  divider: {
    height: 1,
    backgroundColor: COLORS.NEUTRAL.LOW.LIGHT,
    marginVertical: SPACING.MD,
  },
  productsTitle: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: COLORS.BLACK,
    marginBottom: SPACING.MD,
  },
  orderItemCard: {
    flexDirection: 'row',
    backgroundColor: COLORS.SECONDARY.PURE,
    borderRadius: 28,
    padding: SPACING.MD,
    marginBottom: SPACING.MD,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 16,
    elevation: 4,
  },
  orderItemImage: {
    width: 100,
    height: 100,
    borderRadius: 16,
    marginRight: SPACING.MD,
  },
  orderItemContent: {
    flex: 1,
  },
  orderItemTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.XS,
    marginBottom: SPACING.XS,
  },
  orderItemTag: {
    backgroundColor: COLORS.TEXT,
    paddingHorizontal: SPACING.SM,
    paddingVertical: 4,
    borderRadius: 12,
  },
  orderItemTagText: {
    fontSize: FONT_SIZES.XS,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: COLORS.WHITE,
  },
  orderItemTitle: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: COLORS.TEXT,
    marginBottom: SPACING.XS,
  },
  orderItemSubtitle: {
    fontSize: FONT_SIZES.XS,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: COLORS.TEXT_LIGHT,
    marginBottom: SPACING.XS,
  },
  orderItemMeta: {
    fontSize: FONT_SIZES.XS,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: COLORS.TEXT_LIGHT,
    marginBottom: SPACING.XS,
  },
  orderItemFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: SPACING.XS,
    marginBottom: SPACING.XS,
  },
  orderItemPrice: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: COLORS.TEXT,
  },
  orderItemQuantity: {
    fontSize: FONT_SIZES.XS,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: COLORS.TEXT_LIGHT,
  },
  orderItemActionButton: {
    borderWidth: 1,
    borderColor: COLORS.TEXT,
    borderRadius: 18,
    paddingVertical: SPACING.XS,
    paddingHorizontal: SPACING.SM,
    alignSelf: 'flex-start',
    marginTop: SPACING.XS,
  },
  orderItemActionButtonText: {
    fontSize: FONT_SIZES.XS,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: COLORS.TEXT,
  },
  orderItemCanceledTag: {
    borderRadius: 18,
    paddingVertical: SPACING.XS,
    paddingHorizontal: SPACING.SM,
    alignSelf: 'flex-start',
    marginTop: SPACING.XS,
    backgroundColor: COLORS.NEUTRAL.LOW.MEDIUM,
  },
  orderItemCanceledTagText: {
    fontSize: FONT_SIZES.XS,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: COLORS.WHITE,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: SPACING.XL,
  },
  errorText: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    color: COLORS.FEEDBACK.WARNING,
    textAlign: 'center',
    marginBottom: SPACING.MD,
  },
  footer: {
    paddingHorizontal: SPACING.MD,
    paddingBottom: SPACING.MD,
    paddingTop: SPACING.SM,
  },
  backButton: {
    width: '100%',
  },
});
