import { StyleSheet } from 'react-native';
import { SPACING, FONT_SIZES } from '@/constants';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
    position: 'relative',
  },
  contentFloatingMenuReserve: {
    paddingBottom: SPACING.XXL * 1.5,
  },
  listWrap: {
    flex: 1,
    position: 'relative',
    zIndex: 1,
  },
  backgroundLayer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 0,
  },
  scrollView: {
    flex: 1,
    zIndex: 1,
  },
  scrollContent: {
    flexGrow: 1,
  },
  screenTitle: {
    fontSize: FONT_SIZES.XL,
    fontWeight: '700',
    color: '#001137',
    paddingHorizontal: SPACING.LG,
    marginTop: SPACING.MD,
    marginBottom: SPACING.SM,
  },
  warningBanner: {
    backgroundColor: '#edec80',
    borderRadius: 24,
    padding: SPACING.LG,
    marginHorizontal: SPACING.MD,
    marginBottom: SPACING.LG,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 16,
    elevation: 8,
  },
  warningText: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#001137',
    lineHeight: 20,
    letterSpacing: 0.2,
  },
  productsTitle: {
    fontSize: FONT_SIZES.SM,
    fontWeight: '500',
    color: '#000000',
    opacity: 0.8,
    paddingHorizontal: SPACING.MD,
    marginBottom: SPACING.MD,
  },
  cartItemsList: {
    paddingHorizontal: SPACING.MD,
    gap: SPACING.MD,
  },
  billingPeriodRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.SM,
    marginTop: SPACING.SM,
  },
  billingPeriodOption: {
    borderWidth: 1,
    borderColor: '#E1DFCF',
    borderRadius: 12,
    paddingHorizontal: SPACING.SM,
    paddingVertical: SPACING.XS,
    backgroundColor: '#FFFFFF',
  },
  billingPeriodOptionSelected: {
    borderColor: '#0154F8',
    backgroundColor: '#F3F7FF',
  },
  billingPeriodLabel: {
    fontSize: FONT_SIZES.XS,
    color: '#001137',
  },
  billingPeriodLabelSelected: {
    color: '#0154F8',
    fontWeight: '600',
  },
  billingPeriodPrice: {
    fontSize: FONT_SIZES.XS,
    color: '#6e6a6a',
  },
  cartItemWrapper: {
    marginHorizontal: SPACING.MD,
    marginBottom: SPACING.MD,
  },
  shippingSection: {
    paddingHorizontal: SPACING.LG,
    paddingVertical: SPACING.MD,
    gap: SPACING.SM,
  },
  shippingTitle: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#000000',
    marginBottom: SPACING.SM,
  },
  shippingInputRow: {
    flexDirection: 'row',
    gap: SPACING.MD,
    alignItems: 'flex-start',
  },
  zipCodeInput: {
    flex: 1,
    backgroundColor: '#fdfbee',
    borderRadius: 18,
    paddingHorizontal: SPACING.MD,
    paddingVertical: 12,
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#6e6a6a',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    letterSpacing: 0.2,
  },
  applyButton: {
    backgroundColor: '#001137',
    borderRadius: 18,
    paddingHorizontal: SPACING.MD,
    paddingVertical: 9,
    minHeight: 36,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  applyButtonText: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#ffffff',
    textAlign: 'center',
  },
  dontKnowZipButton: {
    alignItems: 'flex-start',
    justifyContent: 'center',
    paddingVertical: 4,
  },
  dontKnowZipText: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#6e6a6a',
    textDecorationLine: 'underline',
    letterSpacing: 0.2,
  },
  orderSummary: {
    paddingHorizontal: SPACING.LG,
    paddingTop: SPACING.MD,
    gap: SPACING.SM,
  },
  separator: {
    height: 1,
    backgroundColor: '#e1dfcf',
    marginVertical: SPACING.SM,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  summaryLabel: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#000000',
    letterSpacing: 0.2,
  },
  summaryValue: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#000000',
    textAlign: 'right',
    letterSpacing: 0.2,
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: SPACING.SM,
  },
  totalLabel: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#000000',
  },
  totalValue: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#000000',
    textAlign: 'right',
  },
  buyButton: {
    width: '100%',
    alignSelf: 'center',
    marginTop: SPACING.LG,
    marginBottom: 0,
  },
  buyButtonContainer: {
    marginHorizontal: SPACING.MD,
    marginVertical: SPACING.MD,
  },
  loadingContainer: {
    padding: SPACING.XL,
    alignItems: 'center',
  },
  loadingText: {
    fontSize: FONT_SIZES.MD,
    color: '#666666',
  },
  emptyCartContainer: {
    padding: SPACING.XL,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 200,
  },
  emptyCartText: {
    fontSize: FONT_SIZES.LG,
    fontWeight: '500',
    color: '#666666',
    marginBottom: SPACING.LG,
  },
  shopButton: {
    backgroundColor: '#001137',
    borderRadius: 24,
    paddingHorizontal: SPACING.LG,
    paddingVertical: SPACING.MD,
    minHeight: 48,
    justifyContent: 'center',
    alignItems: 'center',
  },
  shopButtonText: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#ffffff',
    textAlign: 'center',
  },
});
