import { Platform, StyleSheet } from 'react-native';
import { COLORS, FONT_FAMILY, SPACING } from '@/constants';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingBottom: 0,
    backgroundColor: COLORS.BACKGROUND,
  },
  scrollContent: {
    flexGrow: 1,
    paddingTop: SPACING.LG,
    paddingHorizontal: SPACING.MD,
    paddingBottom: SPACING.XXL,
    gap: SPACING.LG,
  },
  title: {
    fontFamily: FONT_FAMILY.DM_SANS_BOLD,
    fontSize: 20,
    lineHeight: 24,
    color: COLORS.TEXT,
  },
  reasonSection: {
    width: '100%',
    gap: SPACING.MD_PLUS,
  },
  reasonTitleRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'baseline',
    gap: SPACING.XS,
  },
  reasonTitle: {
    fontFamily: FONT_FAMILY.DM_SANS_BOLD,
    fontSize: 16,
    lineHeight: 20,
    color: COLORS.TEXT,
  },
  reasonOptional: {
    fontFamily: FONT_FAMILY.DM_SANS_REGULAR,
    fontSize: 14,
    lineHeight: 18,
    letterSpacing: 0.2,
    color: COLORS.TEXT_LIGHT,
  },
  reasonList: {
    width: '100%',
    gap: SPACING.SM,
  },
  reasonOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.MD_PLUS,
    padding: SPACING.MD,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.SECONDARY.MEDIUM,
    backgroundColor: COLORS.WHITE,
  },
  reasonOptionSelected: {
    borderColor: COLORS.PRIMARY.PURE,
    backgroundColor: COLORS.SECONDARY.LIGHT,
  },
  reasonRadio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.TEXT,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.WHITE,
  },
  reasonRadioSelected: {
    borderColor: COLORS.PRIMARY.PURE,
    padding: 4,
  },
  reasonRadioInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: COLORS.PRIMARY.PURE,
  },
  reasonLabel: {
    flex: 1,
    fontFamily: FONT_FAMILY.DM_SANS_REGULAR,
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.2,
    color: COLORS.TEXT,
  },
  card: {
    width: '100%',
    backgroundColor: COLORS.WHITE,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 28,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 32,
    padding: SPACING.MD,
    gap: SPACING.GAP_20,
  },
  cardTitle: {
    fontFamily: FONT_FAMILY.DM_SANS_BOLD,
    fontSize: 16,
    lineHeight: 20,
    color: COLORS.TEXT,
  },
  consequenceList: {
    width: '100%',
    gap: SPACING.MD_PLUS,
  },
  consequenceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.XS,
    width: '100%',
  },
  consequenceText: {
    flex: 1,
    fontFamily: FONT_FAMILY.DM_SANS_REGULAR,
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.2,
    color: COLORS.TEXT,
  },
  separator: {
    height: StyleSheet.hairlineWidth,
    width: '100%',
    backgroundColor: COLORS.SECONDARY.MEDIUM,
  },
  fieldList: {
    width: '100%',
    gap: SPACING.MD_PLUS,
  },
  fieldBlock: {
    width: '100%',
    gap: SPACING.XS,
  },
  fieldLabel: {
    fontFamily: FONT_FAMILY.DM_SANS_REGULAR,
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.2,
    color: COLORS.TEXT,
  },
  fieldValue: {
    fontFamily: FONT_FAMILY.DM_SANS_REGULAR,
    fontSize: 14,
    lineHeight: 18,
    letterSpacing: 0.2,
    color: COLORS.TEXT_LIGHT,
  },
  actionsRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: SPACING.MD,
    width: '100%',
  },
  actionPrimary: {
    flex: 1,
    minHeight: 48,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
    paddingVertical: 12,
    ...Platform.select({
      ios: {
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
      },
      android: {
        elevation: 2,
      },
      default: {},
    }),
  },
  actionSecondary: {
    flexShrink: 0,
    backgroundColor: 'rgba(240, 238, 225, 0.16)',
    borderColor: COLORS.TEXT,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
    minHeight: 48,
    paddingVertical: 12,
    overflow: 'visible',
    ...Platform.select({
      ios: {
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
      },
      android: {
        elevation: 2,
      },
      default: {},
    }),
  },
});
