import { StyleSheet } from 'react-native';
import { COLORS, SPACING, TYPOGRAPHY } from '@/constants';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingBottom: 0,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'space-between',
    paddingBottom: SPACING.GAP_20,
  },
  gradientOverlay: {
    position: 'absolute',
    top: -50,
    left: 0,
    right: 0,
    height: 280,
    opacity: 0.85,
  },
  profileSection: {
    alignItems: 'center',
    paddingTop: SPACING.LG,
    paddingHorizontal: SPACING.XL,
    gap: SPACING.LG,
  },
  avatarBlock: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatar: {
    width: 116,
    height: 116,
    borderRadius: 58,
    backgroundColor: COLORS.NEUTRAL.LOW.LIGHT,
  },
  avatarPlaceholder: {
    width: 116,
    height: 116,
    borderRadius: 58,
    backgroundColor: COLORS.NEUTRAL.LOW.LIGHT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarEditButton: {
    position: 'absolute',
    right: -8,
    bottom: 4,
  },
  userInfo: {
    alignItems: 'center',
    gap: 2,
    width: '100%',
  },
  userName: {
    ...TYPOGRAPHY.displaySm,
    color: COLORS.TEXT,
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  userEmail: {
    ...TYPOGRAPHY.bodySm,
    color: COLORS.TEXT,
    textAlign: 'center',
  },
  skeletonLine: {
    backgroundColor: COLORS.NEUTRAL.LOW.LIGHT,
    borderRadius: 8,
  },
  skeletonName: {
    width: 200,
    height: 24,
  },
  skeletonEmail: {
    width: 160,
    height: 12,
    marginTop: 4,
  },
  skeletonAvatar: {
    width: 116,
    height: 116,
    borderRadius: 58,
  },
  interestsSection: {
    width: '100%',
    alignItems: 'center',
    gap: SPACING.LG,
  },
  interestsHeaderRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  interestsTitle: {
    fontFamily: 'Instrument Sans',
    fontSize: 15.2,
    fontWeight: '500',
    lineHeight: 15.2,
    color: COLORS.TEXT,
  },
  addInterestButton: {
    position: 'absolute',
    right: 0,
  },
  interestsTagsRow: {
    width: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.SM,
    justifyContent: 'center',
  },
  interestTag: {
    flexGrow: 1,
    flexBasis: '45%',
    maxWidth: '48%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    paddingHorizontal: SPACING.MD,
    paddingVertical: 7,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    backgroundColor: 'rgba(251, 247, 229, 0.8)',
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  interestTagLabel: {
    ...TYPOGRAPHY.labelMd,
    color: COLORS.TEXT,
    flexShrink: 1,
  },
  emptyInterestsText: {
    ...TYPOGRAPHY.bodyMdMedium,
    color: COLORS.TEXT_LIGHT,
    textAlign: 'center',
  },
  manageSection: {
    width: '100%',
    paddingHorizontal: SPACING.MD,
    gap: SPACING.MD,
    marginTop: SPACING.XL,
  },
  manageSectionTitle: {
    fontFamily: 'DM Sans',
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 24,
    color: COLORS.TEXT,
  },
  menuList: {
    width: '100%',
  },
  menuItemBlock: {
    paddingTop: SPACING.LG,
    gap: SPACING.MD,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  menuItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.SM,
    flex: 1,
  },
  menuItemLabel: {
    fontFamily: 'DM Sans',
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 24,
    color: COLORS.TEXT,
    flexShrink: 1,
  },
  menuItemDisabled: {
    opacity: 0.45,
  },
  menuItemLabelDisabled: {
    color: COLORS.TEXT_LIGHT,
  },
  separator: {
    height: 1,
    backgroundColor: COLORS.SECONDARY.MEDIUM,
    width: '100%',
  },
});
