export const SUBSCRIPTION_STATUS = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  PAST_DUE: 'PAST_DUE',
  UNPAID: 'UNPAID',
  CANCELED: 'CANCELED',
} as const;

export type SubscriptionStatusKey = (typeof SUBSCRIPTION_STATUS)[keyof typeof SUBSCRIPTION_STATUS];

export const SUBSCRIPTION_STATUSES_WITH_PROTOCOL_ACCESS: readonly SubscriptionStatusKey[] = [
  SUBSCRIPTION_STATUS.ACTIVE,
  SUBSCRIPTION_STATUS.PAST_DUE,
];

export const SUBSCRIPTION_STATUSES_ALLOWING_PAYMENT_METHOD_UPDATE: readonly SubscriptionStatusKey[] = [
  SUBSCRIPTION_STATUS.PAST_DUE,
  SUBSCRIPTION_STATUS.UNPAID,
];
