import { StyleSheet, Dimensions } from 'react-native';
import { SPACING } from '@/constants';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const styles = StyleSheet.create({
  section: {
    width: SCREEN_WIDTH,
    position: 'relative',
  },
  cardContainer: {
    position: 'absolute',
    bottom: SPACING.LG,
    right: SPACING.MD,
    left: SPACING.MD,
    alignItems: 'flex-end',
  },
  image: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  desaturatedImageWrap: {
    ...StyleSheet.absoluteFillObject,
    filter: [{ grayscale: 1 }],
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    overflow: 'hidden',
  },
  imageStyle: {
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
  },
  bottomBlock: {
    position: 'relative',
    alignSelf: 'stretch',
    width: '100%',
    paddingHorizontal: SPACING.LG,
    minHeight: 56,
  },
  effectsContainer: {
    ...StyleSheet.absoluteFillObject,
    overflow: 'hidden',
    zIndex: 0,
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
  },
  gradient: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    zIndex: 0,
  },
  blur: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    overflow: 'hidden',
    zIndex: 0,
  },
  content: {
    zIndex: 2,
    paddingBottom: SPACING.XS,
  },
  badgesContainer: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 10,
    paddingTop: SPACING.MD,
  },
  badgesContainerCompact: {
    marginBottom: 4,
  },
  badge: {
    backgroundColor: 'rgba(0, 17, 55, 0.64)',
    paddingHorizontal: 14,
    paddingVertical: 0,
    borderRadius: 16,
    minHeight: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  badgeText: {
    fontSize: 12,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#f6dea9',
    letterSpacing: 0.2,
  },
  title: {
    fontSize: 20,
    fontFamily: 'DM Sans',
    fontStyle: 'normal',
    fontWeight: '700',
    color: '#FFFFFF',
    lineHeight: 22,
    letterSpacing: 0.2,
  },
  name: {
    fontSize: 20,
    fontFamily: 'DM Sans',
    fontStyle: 'normal',
    fontWeight: '700',
    color: '#FFFFFF',
    marginTop: 8,
    lineHeight: 22,
    letterSpacing: 0.2,
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 16,
    width: '100%',
  },
});
