import { StyleSheet } from 'react-native';
import {
  BORDER_RADIUS,
  COLORS,
  FONT_FAMILY,
  FONT_SIZES,
  SPACING,
  FLOATING_NAV_MENU_BAR_OFFSET,
  TYPOGRAPHY,
} from '@/constants';

const cardRadius = {
  borderTopLeftRadius: BORDER_RADIUS.XL,
  borderTopRightRadius: 28,
  borderBottomRightRadius: SPACING.XL,
  borderBottomLeftRadius: BORDER_RADIUS.MD,
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.BACKGROUND,
  },
  scrollContent: {
    paddingBottom: SPACING.XL + FLOATING_NAV_MENU_BAR_OFFSET,
  },
  infoSection: {
    paddingHorizontal: SPACING.LG,
    paddingTop: SPACING.LG,
    gap: SPACING.SM,
  },
  sectionTitle: {
    ...TYPOGRAPHY.bodyMdMedium,
    color: COLORS.NEUTRAL.LOW.PURE,
  },
  tabContent: {
    paddingTop: SPACING.LG,
    gap: SPACING.LG,
  },
  eventBannerContainer: {
    paddingHorizontal: SPACING.MD,
    width: '100%',
    alignSelf: 'stretch',
  },
  descriptionText: {
    ...TYPOGRAPHY.bodyMd,
    color: COLORS.NEUTRAL.LOW.DARK,
    paddingHorizontal: SPACING.LG,
  },
  emptyText: {
    ...TYPOGRAPHY.bodyMd,
    color: COLORS.NEUTRAL.LOW.DARK,
    paddingHorizontal: SPACING.LG,
  },
  loaderWrap: {
    paddingVertical: SPACING.XXL,
    alignItems: 'center',
  },
  heroFooter: {
    width: '100%',
  },
  heroDescription: {
    ...TYPOGRAPHY.bodySm,
    color: COLORS.WHITE,
    marginBottom: SPACING.SM,
  },
  headerTitle: {
    fontFamily: FONT_FAMILY.DM_SANS_BOLD,
    fontSize: 16,
    lineHeight: 20,
    color: COLORS.TEXT,
    maxWidth: 220,
    textAlign: 'center',
  },
  canceledNoticeCard: {
    marginHorizontal: SPACING.MD,
    backgroundColor: COLORS.BACKGROUND_SECONDARY,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 32,
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 24,
    padding: SPACING.LG,
  },
  canceledNoticeText: {
    ...TYPOGRAPHY.bodyMd,
    color: COLORS.TEXT,
  },
  canceledNoticeDate: {
    fontFamily: FONT_FAMILY.DM_SANS_BOLD,
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0.2,
    color: COLORS.TEXT,
  },
  similarProductsSection: {
    paddingHorizontal: SPACING.MD,
    alignItems: 'center',
    gap: SPACING.MD,
  },
  similarProductsTitle: {
    ...TYPOGRAPHY.title3,
    color: COLORS.TEXT,
    textAlign: 'center',
  },
  similarProductsDescription: {
    ...TYPOGRAPHY.bodyMd,
    color: COLORS.TEXT,
    textAlign: 'center',
    maxWidth: 275,
  },
  journeyRoot: {
    paddingHorizontal: SPACING.LG,
    paddingTop: SPACING.LG,
    gap: SPACING.XL,
  },
  welcomeBlock: {
    gap: SPACING.MD,
  },
  welcomeHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: SPACING.SM,
  },
  welcomeTitle: {
    flex: 1,
  },
  manageButton: {
    flexShrink: 0,
    minHeight: 36,
    paddingHorizontal: SPACING.MD,
    paddingVertical: SPACING.SM,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.WHITE,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderBottomRightRadius: BORDER_RADIUS.LG,
    borderBottomLeftRadius: BORDER_RADIUS.LG,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 4,
  },
  manageButtonOpen: {
    backgroundColor: COLORS.PRIMARY.PURE,
  },
  menuBackdrop: {
    flex: 1,
  },
  menuDismissArea: {
    ...StyleSheet.absoluteFillObject,
  },
  menuCard: {
    position: 'absolute',
    zIndex: 2,
    minWidth: 165,
    minHeight: 48,
    paddingHorizontal: SPACING.MD,
    paddingVertical: SPACING.MD_PLUS,
    gap: SPACING.MD_PLUS,
    backgroundColor: COLORS.SECONDARY.LIGHT,
    borderWidth: 1,
    borderColor: COLORS.PRIMARY.PURE,
    borderTopLeftRadius: BORDER_RADIUS.XL,
    borderTopRightRadius: BORDER_RADIUS.XL,
    borderBottomRightRadius: BORDER_RADIUS.BUTTON_BOTTOM,
    borderBottomLeftRadius: BORDER_RADIUS.BUTTON_BOTTOM,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 4,
  },
  menuOption: {
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  menuOptionLabel: {
    fontFamily: FONT_FAMILY.DM_SANS_MEDIUM,
    fontSize: FONT_SIZES.SM,
    lineHeight: 18,
    color: COLORS.PRIMARY.PURE,
    textAlign: 'left',
  },
  displayTitle: {
    ...TYPOGRAPHY.displaySm,
    color: COLORS.NEUTRAL.LOW.PURE,
    textTransform: 'uppercase',
  },
  welcomeBody: {
    ...TYPOGRAPHY.bodyMd,
    color: COLORS.NEUTRAL.LOW.PURE,
  },
  section: {
    gap: SPACING.SM,
  },
  sectionLabel: {
    ...TYPOGRAPHY.bodyMdMedium,
    color: COLORS.NEUTRAL.LOW.PURE,
  },
  continueCard: {
    ...cardRadius,
    backgroundColor: COLORS.PRIMARY.LIGHT,
    flexDirection: 'row',
    gap: SPACING.LG,
    paddingHorizontal: SPACING.GAP_20,
    paddingVertical: SPACING.MD,
    minHeight: 187,
  },
  continueCover: {
    width: 118,
    height: 154,
    borderTopLeftRadius: SPACING.GAP_20,
    borderTopRightRadius: SPACING.GAP_20,
    borderBottomRightRadius: SPACING.GAP_20,
    borderBottomLeftRadius: BORDER_RADIUS.MD,
  },
  continueCopy: {
    flex: 1,
    justifyContent: 'space-between',
    gap: SPACING.SM,
  },
  overline: {
    ...TYPOGRAPHY.bodySmRegular,
    color: COLORS.NEUTRAL.LOW.DARK,
    textTransform: 'uppercase',
  },
  continueTitle: {
    fontFamily: FONT_FAMILY.DM_SANS_BOLD,
    fontSize: FONT_SIZES.MD,
    lineHeight: 20,
    color: COLORS.NEUTRAL.LOW.PURE,
  },
  continueSummary: {
    ...TYPOGRAPHY.bodySm,
    color: COLORS.TEXT_LIGHT,
  },
  liveSection: {
    gap: SPACING.MD,
  },
  liveLabel: {
    fontFamily: FONT_FAMILY.DM_SANS_SEMIBOLD,
    fontSize: FONT_SIZES.SM,
    lineHeight: 18,
    color: COLORS.NEUTRAL.LOW.PURE,
  },
  liveRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  liveCoverFrame: {
    width: 139,
    height: 148,
    ...cardRadius,
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 16,
    elevation: 2,
  },
  liveCoverWrap: {
    flex: 1,
    ...cardRadius,
    overflow: 'hidden',
    justifyContent: 'flex-end',
    padding: SPACING.MD_PLUS,
  },
  liveCover: {
    ...StyleSheet.absoluteFillObject,
  },
  liveCoverFallback: {
    backgroundColor: COLORS.SECONDARY.MEDIUM,
  },
  liveCoverShade: {
    ...StyleSheet.absoluteFillObject,
  },
  liveAction: {
    minHeight: 36,
    paddingHorizontal: SPACING.MD,
    paddingVertical: SPACING.SM,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.SECONDARY.LIGHT,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderBottomRightRadius: BORDER_RADIUS.LG,
    borderBottomLeftRadius: BORDER_RADIUS.LG,
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  liveActionLabel: {
    fontFamily: FONT_FAMILY.DM_SANS_MEDIUM,
    fontSize: FONT_SIZES.SM,
    lineHeight: 18,
    color: COLORS.NEUTRAL.LOW.PURE,
    textAlign: 'center',
  },
  livePanel: {
    flex: 1,
    height: 148,
    ...cardRadius,
    backgroundColor: `${COLORS.HIGHLIGHT.LIGHT}CC`,
    padding: SPACING.MD,
    justifyContent: 'center',
    gap: SPACING.XL,
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 16,
    elevation: 2,
  },
  liveCopy: {
    gap: SPACING.SM,
  },
  liveMessage: {
    ...TYPOGRAPHY.bodyMd,
    color: COLORS.NEUTRAL.LOW.PURE,
  },
  liveWhen: {
    fontFamily: FONT_FAMILY.DM_SANS_BOLD,
    fontSize: FONT_SIZES.MD,
    lineHeight: 20,
    color: COLORS.NEUTRAL.LOW.PURE,
  },
  journeyHeader: {
    gap: SPACING.SM,
  },
  journeyHint: {
    ...TYPOGRAPHY.bodyMd,
    color: COLORS.NEUTRAL.LOW.PURE,
  },
  stageList: {
    gap: SPACING.LG,
  },
  archiveSection: {
    gap: SPACING.MD,
  },
  archiveCard: {
    height: 164,
    overflow: 'hidden',
    ...cardRadius,
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  archivePhoto: {
    ...StyleSheet.absoluteFillObject,
  },
  archiveShade: {
    ...StyleSheet.absoluteFillObject,
  },
  archiveCopy: {
    flex: 1,
    justifyContent: 'flex-end',
    padding: SPACING.MD,
    gap: SPACING.SM,
  },
  archiveBadge: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(0, 17, 55, 0.64)',
    borderRadius: BORDER_RADIUS.SM,
    paddingHorizontal: SPACING.SM,
    paddingVertical: 2,
  },
  archiveBadgeText: {
    fontFamily: FONT_FAMILY.DM_SANS_MEDIUM,
    fontSize: FONT_SIZES.XS,
    lineHeight: 22,
    color: '#F6DEA9',
  },
  archiveBody: {
    ...TYPOGRAPHY.bodyMd,
    color: COLORS.WHITE,
  },
  archiveButton: {
    alignSelf: 'flex-start',
    minHeight: 36,
    justifyContent: 'center',
    paddingHorizontal: SPACING.MD,
    borderWidth: 1,
    borderColor: COLORS.SECONDARY.LIGHT,
    backgroundColor: 'rgba(240, 238, 225, 0.16)',
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderBottomLeftRadius: BORDER_RADIUS.MD,
    borderBottomRightRadius: BORDER_RADIUS.MD,
  },
  archiveButtonLabel: {
    fontFamily: FONT_FAMILY.DM_SANS_MEDIUM,
    fontSize: FONT_SIZES.SM,
    lineHeight: 18,
    color: COLORS.WHITE,
  },
});
